### ISSUE TITLE
没有判断token过期

### ISSUE THREAD

**Issue by zhudan** [node-webot/wechat-enterprise-api#21]

**Comment by JacksonTian** [comment]
有判断的，你是怎么使用的？

**Comment by zhudan** [comment]
@JacksonTian 
https://github.com/node-webot/wechat-enterprise-api/blob/master/lib/api_common.js#L171  木有看到判断token的代码

**Comment by JacksonTian** [comment]
企业版有点不同。所以没有先用时间来判断，而是调用发现token超时后 再刷新token重新调用。

**Comment by zhudan** [comment]
目前也只能先这样做啦
